---
title: "R Notebook"
output: html_notebook
---

## 1.5 Analysis

```{r}
library(tidyverse)

```

manually adding reflectance data.
```{r}
s_sens <- 4.49 # sensor sensitivity 10e-6 V / W m-2
sw_in <- 3.12 * 1000 / s_sens
refl <- tribble(
  ~ surface,  ~ voltage,
  "grass" ,  0.71,
  "grass" ,  0.76,
  "road",  0.78,
  "road",  0.81,
  "asphalt",  0.3
) %>%
  mutate(radiation = voltage * 1000 / s_sens, # need to convert micro volts in mV
         albedo = radiation / sw_in) %>%
  group_by(surface, )%>%
  summarize_all(mean)
```

```{r}
trans <- read_csv("data/sw_transmitted_canopy.csv", comment = "#") %>%
  mutate(radiation = voltage * 1000 / s_sens, # need to convert micro volts in mV
         frac_trans = radiation / sw_in, 
         x=seq_along(radiation))

frac_trans_mean <- mean(trans$frac_trans)
frac_trans_sd <- sd(trans$frac_trans)
```

```{r}
ggplot(refl) +
  geom_bar(aes(x=surface, y=albedo, fill=surface), stat="identity") +
  geom_label(aes(x=surface, y=albedo, label=paste(round(albedo, 2), "%"))) +
  scale_fill_manual(values=c("grass" = "#009A17",
                             "road" = "#D3BC8D",
                             "asphalt" = "#807E78"),
                    ) +
  ylim(0,1) +
  labs(title="Albedo on different surfaces", x= "Surface", y="Albedo (%)")
 
```
```{r}
ggplot(trans) + 
  geom_path(aes(x=x, y=frac_trans), colour="red")+
  geom_hline(yintercept = frac_trans_mean, linetype="dotted") +
  ylim(0,1)+
  labs(title="Transmitted sw over transect in forest", x="lenght (m)", y="Fraction transmitted (%)",
       subtitle = paste("Mean transmitted radiation: ", round(frac_trans_mean, 2), ", Sd: ", round(frac_trans_sd,2)))
```

