---
title: "R Notebook"
output: html_notebook
---
AIR TEMPERATURE

1.1 Motivation
- briefly explain the relevance of the variable from an ecosystem perspective

As it is known from previous background information, ecosystems are characterized by the regulation that occur due to different variables. More concretely, one of these variables is air temperature. Air temperature has a main role in the activeness of photosynthesis activity. The higher the temperature of air is, the higher the hydric stress plants are facing. In some species, when the temperature is higher the fixation of $CO_2$ occur with a higher rate than others. 


1.2 Background
- describe the most important background needed to fulfill the excercises, 
- list necessary equations
- maybe include calibration coefficients for reproducibility and when necessary

What is temperature?

Temperature is defines as a state variable, which describes the mean kinetic energy of molecules. Some of the units used to measure temperature are K, ºF, Cº. 

$$E_ = 1/2*m*v^2 = 3/2*k*T$$ with $k$ as $1.381*10-23$, $m$ as mass in $kg$, $v$ of velocity in $m/s$ and $T$ in K. 

In order to measure temperature correctly, there are some scales and units fixed as they were mentioned above. T = 0 (K) is the temperature to have in mind when molecular motion is none. Other values used to have some reference between the units used are:

0 (K) = -273.15 (ºC)        273.15 (K) = 0.0 (ºC)       273.16(K) = 0.01 (ºC)






Another important factor to be aware of, is the possibility of an adiabatic process to occur. These processes are characterized because of the lack of heat transfer between its close atmosphere. 


1.4 Sensors and measuring principle
- here list available sensors (maybe include picture) to measure the respective variables and briefly explain its measuring concepts, I.e. Pyranometer is used to measure global, diffuse and reflected radiation, based on thermopiles...


In case of temperature, the measurement
1.5 Analysis

In this section you present two figures related to each of the two excercises you’ve chosen for the report. Use the figures as basis for your discussion and firstly describe what you see on the figure and secondly discuss possible reasons. If possible include scientific literature for your discussions. 

Figures should have meaningful labels on the x and y axes, if necessary a title. The labels should include units. Please include a caption beneath each figure. 

