---
title: "10th Protocol: Turbulent fluxes"
author: "Cheyenne Rueda and Simone Massaro"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document:
    toc: true
    number_sections: true
    includes:
      in_header: "../preamble.tex"
  html_notebook:
    number_sections: true
header-includes:
  - \fancyhead[L]{Turbulent fluxes}
editor_options: 
  markdown: 
    wrap: 72
---

# Motivation

# Background

# Sensors and measuring principle

# Analysis

1.
Calculate the half hourly latent heat flux, the net ecosystem exchange of CO 2 and the sensible heat flux from the high frequency turbulence data. 
```{r}
library(tidyverse)
```




## Respiration chambers

```{r}
co2 <- read_csv2("../Data_lectures/soilCO2flux.csv",
                 col_names=c("time", "co2", "chamber"), skip=1)
# loading some data directly from in the R code for simplicity
p_a <- 989.5 #hPa - air pressure
T_a <- 16 + 273.15 # °C - air temperature
diam <- 0.152 # m - radius of chamber
top_height <- 0.138 # m - height of top part of the chamber (same for everything)

# area 
area <- pi / 4 *diam^2

# chamber specific data
chambers <- tribble(
  ~"Tsoil",~"chamber",~"height",
  17,	  1, 0.16225,		
  17,	  2, 0.17,
  16.8,	3, 0.1495,
  16.7,	4, 0.154,
  17.2,	5, 0.159
) %>% 
  mutate(
    Volume= pi / 4 * diam^ 2 * (height+top_height))
# Molar Gas Constant
R <- 8.314 # J/mol K
```

```{r}
# Molar volume 
M <- p_a / (R*T_a)

co2flux <- co2 %>%
  # Adding chamber information
  left_join(chambers) %>% 
  group_by(chamber) %>% 
  mutate(
    dt = time - lag(time),
    dc = co2 - lag(co2),
    Fc = (dc/dt)*(M*Volume/area),
    # for plotting
    chamber = as.factor(chamber)
  )

co2flux
```


```{r}
ggplot(co2flux, aes(time, co2, col=chamber)) +
  geom_line()
```

```{r}
ggplot(co2flux, aes(time, dt/dc, col=chamber)) +
  geom_line()
```
```{r}
ggplot(co2flux, aes(time, Fc, col=chamber)) +
  geom_line()
```

```{r}
ggplot(co2flux, aes(chamber, Fc)) +
  geom_boxplot()
```



## Eddy Covariance

```{r}
library(fs)
library(lubridate)
library(progressr)
```

```{r}
ec_col_names <-  c("TIMESTAMP","TIMESTAMPS","U","V","W","T_SONIC",
                   "SA_DIAG_VALUE","CO2_ABS","H2O_ABS","CO2_CONC",
                   "H2O_CONC","CO2_POW_SAM","H2O_POW_SAM","CO2_POW_REF",
                   "H2O_POW_REF","CO2","H2O","T_CELL","PRESS_CELL",
                   "GA_DIAG_CODE","T_DEW","CO2_STR")
```


```{r}
ec_test_path <- "../Data_lectures/10_Turbulent_fluxes_II/10_Turb_fluxes_CO2/Reinshof_flux_HF_202105300001.dat"
ec <-read_csv(ec_test_path, skip=4, col_names = ec_col_names, na=c("", "NaN"))
```
```{r}
head(ec)
```


# Raw flux calculation

```{r}
# the emp
process_ec_file <- function(file, p=function(){}) {
  ec <-read_csv(file, skip=4, col_names = ec_col_names, col_types = cols())
  time <- str_extract(file, "\\d+.dat$") %>% 
    parse_date_time("YmdHM")
  flux <- calc_fluxes(ec) %>% 
    mutate(time = time)
  p() # step progress bar
  return(flux)
}
```


```{r}
# Molar Gas Constant
R <- 8.314 # J/mol K
calc_fluxes <- function(ec){
  # celsius to kelvin
  T_a <- ec$T_CELL + 273.15
  # need to convert pressure to Pa from kPa
  p_a <- ec$PRESS_CELL * 1e3
  rho_m <- calc_rho_m(p_a, T_a)
  CO2_flux <- calc_CO2_flux(ec$W, ec$CO2, rho_m)
  #H20_flux <- calc_H20_flux(w, h2o)
  tibble(co2 = CO2_flux, rho=rho_m)
}

calc_CO2_flux <- function(w, co2, rho_m){
  cov(w, co2, use="complete.obs") * rho_M
}

calc_rho_m <- function(p, T_a){
  mean( p / (R * T_a), na.rm=T)
}
```
```{r}
calc_fluxes(ec_test)
```


```{r}
process_ec_file(ec_test_path)
```


```{r}
files <- dir_ls("../Data_lectures/10_Turbulent_fluxes_II/10_Turb_fluxes_CO2/")
with_progress({
  # this is to have a progress bar
  p <- progressor(along=files)
  ec_flux <- map_dfr(files, process_ec_file, p)
})
```

```{r}
ggplot(ec_flux, aes(time, co2)) +
  geom_hline(yintercept = 0, linetype=2) +
  geom_line()
```
#### Despike
```{r}
# data is a vector, need to find a better name
despike <- function(data, times_sd = 5) {
  #browser()
  mean_data <- mean(data, na.rm=T)
  sd_data <- sd(data, na.rm=T)
  spikes <- abs(data - mean_data) > (times_sd*sd_data)
  # spikes will be NAs
  data[spikes] <- NA
  return(data)
}
```

```{r}
co2_mean <- mean(ec_test$CO2, na.rm=T)
co2_sd <- sd(ec_test$CO2, na.rm=T)
ggplot(ec_test, aes(TIMESTAMP, CO2)) +
  geom_line() +
  geom_hline(yintercept = co2_mean) +
  geom_hline(yintercept = c(co2_mean + co2_sd, co2_mean - co2_sd), linetype=2)
```

```{r}
co2_mean <- mean(ec_test$CO2, na.rm=T)
co2_sd <- sd(ec_test$CO2, na.rm=T) * 1.5
ggplot(ec_test, aes(TIMESTAMP, despike(CO2, times_sd = 1.5))) +
  geom_hline(yintercept = co2_mean) +
  geom_hline(yintercept = c(co2_mean + co2_sd, co2_mean - co2_sd), linetype=2) +
  geom_line(aes(y = CO2), color="grey50") +
  geom_line()
```


### Rotations

rotations are for later 
```{r}

```

### Time lag correction

```{r}
# maybe find a better name, lag that supports negative values
lag2 <- function(x, n){
  ifelse(n => 0, lag(x, n), lead(x, -n))
}
```

```{r}
lagged_cov <- function(w, gas, range=20){
  map(seq(-range, range), function(n){
    cov(w, lag2(gas, n), use="complete.obs")
  })
}
```

```{r}
lagged_cov(ec$W, ec$CO2)
```

```{r}
cov(ec$W, lead(ec$CO2, 5), use="complete.obs")
```







